{
 "title": "zoo",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "用户", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "游客分布",
   "type": "status-history",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    { "expr": "sum by(location) (user)", "legendFormat": "{{location}}" }
   ]
  },
  {
   "title": "游客数目",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    { "expr": "sum(user)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "门票收入",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    { "expr": "sum(fee)" }
   ]
  },
  {
   "title": "员工和游客数目",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum by(type) (user)", "legendFormat": "{{type}}" }
   ]
  },
  {
   "title": "车辆",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "停车费",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
     "targets": [
      { "expr": "sum(car_fee)" }
     ]
    },
    {
     "title": "车辆总数",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "sum by() (car)", "legendFormat": "{{location}}" }
     ]
    },
    {
     "title": "车辆总数",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 26 },
     "targets": [
      { "expr": "sum(car)" }
     ]
    },
    {
     "title": "车辆总数",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "sum by(type) (car)", "legendFormat": "{{type}}" }
     ]
    },
    {
     "title": "车辆总数",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
     "targets": [
      { "expr": "sum by(type) (car)", "legendFormat": "{{type}}" }
     ]
    }
   ]
  },
  {
   "title": "动物",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "动物数量",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "animal", "legendFormat": "{{type}}" }
     ]
    },
    {
     "title": "数目",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "targets": [
      { "expr": "animal", "legendFormat": "{{type}}" }
     ]
    },
    {
     "title": "长颈鹿数目",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "targets": [
      {
       "expr": "animal{type=\"长颈鹿\"}",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "大象数目",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "targets": [
      {
       "expr": "animal{type=\"大象\"}",
       "legendFormat": "{{type}}"
      }
     ]
    }
   ]
  }
 ]
}